### ISSUE TITLE
Conda package 'docker-py' conflicts with pip package 'docker'

### ISSUE THREAD

**Issue by Bezier89** [conda-forge/docker-py-feedstock#25]
Reproduction steps:

```
conda create -n TestEnv1 docker-py -c conda-forge
conda env export -n TestEnv1 > env.yaml
```

Look at env.yaml and note that the result includes the following pip package (in addition to the conda package `docker-py=3.6.0=py37_1000`)

```
  - pip:
    - docker==3.6.0
```

This is problematic if you're trying to share this environment via the environment file, as the pip and conda packages will stomp over each other (not sure which gets priority), and the pip package will also bring in further pip dependencies. For example, if you now run the following commands:

```
conda env create -n TestEnv2 -f env.yaml
conda env export -n TestEnv2
```

The pip section grows to become:

```
  - pip:
    - docker==3.6.0
    - pypiwin32==223
    - pywin32==224
```

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
          conda version : 4.5.11
    conda-build version : 3.17.6
         python version : 3.6.7.final.0
               platform : win-64
```
</details>

**Comment by jaroslawk** [comment]
@scopatz I would like to use conda based ```docker``` package but strangely there is only ```docker-py``` 
The interesting part is that in pypi ```docker``` and ```docker-py``` point to the same git-repo. 


Should there be also ```docker``` package added to conda?
Is ```docker-py``` obsolete?

**Comment by scopatz** [comment]
docker-py is simply the conda-forge name for what on PyPI is called docker.

**Comment by jaroslawk** [comment]
I have figured it out already :D
